name: Executar Testes Automatizados (Manual)

on:
  workflow_dispatch:  # Permite acionar manualmente

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Evita execuções infinitas

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante o clone completo do histórico

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Cache para instalação mais rápida

      - name: Instalar dependências
        run: npm install  # Usa package-lock.json exatamente

      - name: Executar testes
        run: npm test
        env:
          NODE_ENV: test  # Variável de ambiente para modo teste